### ISSUE TITLE
Twillio Error always visible on load on Campaign audio page

### ISSUE THREAD

**Issue by cadecairos** [spacedogXYZ/call-power#70]
I'm evaluating running a call-power server, and I noticed that `Twillio Error: Invalid application SID` is always visible on page load (even though Twillio works perfectly elsewhere in the application.

![](https://screenshots.firefoxusercontent.com/images/b169e4aa-b95c-4ea1-887f-6fb77e9c3cf9.png)

I'm running v1.3.2

**Comment by jlev** [comment]
Hey Christopher, thanks for checking out CallPower. The "invalid application SID" error may be due to a missing TWILIO_PLAYBACK_APP environment variable. You'd need to create a TwiML app to that calls the `/api/text-to-speech` route, to test playback of the robot voice from the browser.

If that's not the issue, send me an email to josh@spacedog.xyz, and we'll try to debug further.

**Comment by jlev** [comment]
fixed in [v1.3.6](https://github.com/spacedogXYZ/call-power/releases/tag/v1.3.6)
